# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cmarkovstsen_gs <- function(Q, x0, y, pis, steps, rtol, maxiter) {
    .Call('_RMarkov_Cmarkovstsen_gs', PACKAGE = 'RMarkov', Q, x0, y, pis, steps, rtol, maxiter)
}

Ctran_unif_vec <- function(trans, A, x0, t, ufact, eps, rmax) {
    .Call('_RMarkov_Ctran_unif_vec', PACKAGE = 'RMarkov', trans, A, x0, t, ufact, eps, rmax)
}

Ctran_unif_mat <- function(trans, A, x0, t, ufact, eps, rmax) {
    .Call('_RMarkov_Ctran_unif_mat', PACKAGE = 'RMarkov', trans, A, x0, t, ufact, eps, rmax)
}

Ctran_unif_rwd_vec_vec <- function(trans, A, x0, rwd, t, ufact, eps, rmax) {
    .Call('_RMarkov_Ctran_unif_rwd_vec_vec', PACKAGE = 'RMarkov', trans, A, x0, rwd, t, ufact, eps, rmax)
}

Ctran_unif_rwd_vec_mat <- function(trans, A, x0, rwd, t, ufact, eps, rmax) {
    .Call('_RMarkov_Ctran_unif_rwd_vec_mat', PACKAGE = 'RMarkov', trans, A, x0, rwd, t, ufact, eps, rmax)
}

Ctran_unif_rwd_mat_mat <- function(trans, A, x0, rwd, t, ufact, eps, rmax) {
    .Call('_RMarkov_Ctran_unif_rwd_mat_mat', PACKAGE = 'RMarkov', trans, A, x0, rwd, t, ufact, eps, rmax)
}

Cmarkovst_gth <- function(Q) {
    .Call('_RMarkov_Cmarkovst_gth', PACKAGE = 'RMarkov', Q)
}

Cmarkovst_power <- function(Q, x0, ufact, steps, rtol, maxiter) {
    .Call('_RMarkov_Cmarkovst_power', PACKAGE = 'RMarkov', Q, x0, ufact, steps, rtol, maxiter)
}

Cmarkovst_gs <- function(Q, x0, steps, rtol, maxiter) {
    .Call('_RMarkov_Cmarkovst_gs', PACKAGE = 'RMarkov', Q, x0, steps, rtol, maxiter)
}

Cmexp_mix_unif_vec <- function(trans, A, x, w, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexp_mix_unif_vec', PACKAGE = 'RMarkov', trans, A, x, w, t, ufact, eps, rmax)
}

Cmexp_mix_unif_mat <- function(trans, A, x, w, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexp_mix_unif_mat', PACKAGE = 'RMarkov', trans, A, x, w, t, ufact, eps, rmax)
}

Cmexpint_mix_unif_vec <- function(trans, A, x, w, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexpint_mix_unif_vec', PACKAGE = 'RMarkov', trans, A, x, w, t, ufact, eps, rmax)
}

Cmexpint_mix_unif_mat <- function(trans, A, x, w, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexpint_mix_unif_mat', PACKAGE = 'RMarkov', trans, A, x, w, t, ufact, eps, rmax)
}

Cmexp_unif_vec <- function(trans, A, x, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexp_unif_vec', PACKAGE = 'RMarkov', trans, A, x, t, ufact, eps, rmax)
}

Cmexp_unif_mat <- function(trans, A, x, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexp_unif_mat', PACKAGE = 'RMarkov', trans, A, x, t, ufact, eps, rmax)
}

Cmexpint_unif_vec <- function(trans, A, x, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexpint_unif_vec', PACKAGE = 'RMarkov', trans, A, x, t, ufact, eps, rmax)
}

Cmexpint_unif_mat <- function(trans, A, x, t, ufact, eps, rmax) {
    .Call('_RMarkov_Cmexpint_unif_mat', PACKAGE = 'RMarkov', trans, A, x, t, ufact, eps, rmax)
}

#' @export
C_ddot <- function(x, y) {
    .Call('_RMarkov_C_ddot', PACKAGE = 'RMarkov', x, y)
}

#' @export
C_ddot2 <- function(x, y) {
    .Call('_RMarkov_C_ddot2', PACKAGE = 'RMarkov', x, y)
}

#' @export
C_dasum <- function(x) {
    .Call('_RMarkov_C_dasum', PACKAGE = 'RMarkov', x)
}

#' @export
C_idamax <- function(x) {
    .Call('_RMarkov_C_idamax', PACKAGE = 'RMarkov', x)
}

#' @export
C_dcopy <- function(x, y) {
    .Call('_RMarkov_C_dcopy', PACKAGE = 'RMarkov', x, y)
}

#' @export
C_dcopy2 <- function(x, y) {
    .Call('_RMarkov_C_dcopy2', PACKAGE = 'RMarkov', x, y)
}

#' @export
C_dscal <- function(alpha, x) {
    .Call('_RMarkov_C_dscal', PACKAGE = 'RMarkov', alpha, x)
}

#' @export
C_daxpy <- function(alpha, x, y) {
    .Call('_RMarkov_C_daxpy', PACKAGE = 'RMarkov', alpha, x, y)
}

#' @export
C_dfill <- function(x, v) {
    .Call('_RMarkov_C_dfill', PACKAGE = 'RMarkov', x, v)
}

#' @export
C_dgemvT <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvT', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgemvN <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvN', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgerT <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerT', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgerN <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerN', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgemmNN <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemvN_coo <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvN_coo', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgemvT_coo <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvT_coo', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgerN_coo <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerN_coo', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgerT_coo <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerT_coo', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgemmNN_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNN2_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN2_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN2_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN2_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT2_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT2_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT2_coo <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT2_coo', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemvN_csc <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvN_csc', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgemvT_csc <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvT_csc', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgerN_csc <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerN_csc', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgerT_csc <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerT_csc', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgemmNN_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNN2_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN2_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN2_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN2_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT2_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT2_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT2_csc <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT2_csc', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemvN_csr <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvN_csr', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgemvT_csr <- function(alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemvT_csr', PACKAGE = 'RMarkov', alpha, A, x, beta, y)
}

#' @export
C_dgerN_csr <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerN_csr', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgerT_csr <- function(alpha, x, y, A) {
    .Call('_RMarkov_C_dgerT_csr', PACKAGE = 'RMarkov', alpha, x, y, A)
}

#' @export
C_dgemmNN_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNN2_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNN2_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTN2_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTN2_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmNT2_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmNT2_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_dgemmTT2_csr <- function(alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemmTT2_csr', PACKAGE = 'RMarkov', alpha, A, B, beta, C)
}

#' @export
C_unif_dense <- function(Q, ufactor) {
    .Call('_RMarkov_C_unif_dense', PACKAGE = 'RMarkov', Q, ufactor)
}

#' @export
C_unif_csr <- function(Q, ufactor) {
    .Call('_RMarkov_C_unif_csr', PACKAGE = 'RMarkov', Q, ufactor)
}

#' @export
C_unif_csc <- function(Q, ufactor) {
    .Call('_RMarkov_C_unif_csc', PACKAGE = 'RMarkov', Q, ufactor)
}

#' @export
C_unif_coo <- function(Q, ufactor) {
    .Call('_RMarkov_C_unif_coo', PACKAGE = 'RMarkov', Q, ufactor)
}

#' @export
C_mexp_vecT_dense <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecT_dense', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecN_dense <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecN_dense', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecT_csr <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecT_csr', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecN_csr <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecN_csr', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecT_csc <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecT_csc', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecN_csc <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecN_csc', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecT_coo <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecT_coo', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_vecN_coo <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_vecN_coo', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matN_dense <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matN_dense', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matT_dense <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matT_dense', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matN_csr <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matN_csr', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matT_csr <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matT_csr', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matN_csc <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matN_csc', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matT_csc <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matT_csc', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matN_coo <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matN_coo', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexp_matT_coo <- function(Q, t, x, eps, ufactor) {
    .Call('_RMarkov_C_mexp_matT_coo', PACKAGE = 'RMarkov', Q, t, x, eps, ufactor)
}

#' @export
C_mexpint_vecT_dense <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecT_dense', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecN_dense <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecN_dense', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecT_csr <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecT_csr', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecN_csr <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecN_csr', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecT_csc <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecT_csc', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecN_csc <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecN_csc', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecT_coo <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecT_coo', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_vecN_coo <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_vecN_coo', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matT_dense <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matT_dense', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matN_dense <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matN_dense', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matT_csr <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matT_csr', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matN_csr <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matN_csr', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matT_csc <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matT_csc', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matN_csc <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matN_csc', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matT_coo <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matT_coo', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_mexpint_matN_coo <- function(Q, t, x, cy, eps, ufactor) {
    .Call('_RMarkov_C_mexpint_matN_coo', PACKAGE = 'RMarkov', Q, t, x, cy, eps, ufactor)
}

#' @export
C_gth_dense <- function(Q) {
    .Call('_RMarkov_C_gth_dense', PACKAGE = 'RMarkov', Q)
}

#' @export
C_gth_csr <- function(Q) {
    .Call('_RMarkov_C_gth_csr', PACKAGE = 'RMarkov', Q)
}

#' @export
C_gth_csc <- function(Q) {
    .Call('_RMarkov_C_gth_csc', PACKAGE = 'RMarkov', Q)
}

#' @export
C_gth_coo <- function(Q) {
    .Call('_RMarkov_C_gth_coo', PACKAGE = 'RMarkov', Q)
}

#' @export
C_sparse_nnz <- function(A) {
    .Call('_RMarkov_C_sparse_nnz', PACKAGE = 'RMarkov', A)
}

#' @export
C_nrow_dense <- function(A) {
    .Call('_RMarkov_C_nrow_dense', PACKAGE = 'RMarkov', A)
}

#' @export
C_nrow_csr <- function(A) {
    .Call('_RMarkov_C_nrow_csr', PACKAGE = 'RMarkov', A)
}

#' @export
C_nrow_csc <- function(A) {
    .Call('_RMarkov_C_nrow_csc', PACKAGE = 'RMarkov', A)
}

#' @export
C_nrow_coo <- function(A) {
    .Call('_RMarkov_C_nrow_coo', PACKAGE = 'RMarkov', A)
}

#' @export
C_create_csr <- function(A, value, ptr, ind) {
    invisible(.Call('_RMarkov_C_create_csr', PACKAGE = 'RMarkov', A, value, ptr, ind))
}

#' @export
C_sparse_to_dense_csr <- function(A, B) {
    invisible(.Call('_RMarkov_C_sparse_to_dense_csr', PACKAGE = 'RMarkov', A, B))
}

#' @export
C_create_csc <- function(A, value, ptr, ind) {
    invisible(.Call('_RMarkov_C_create_csc', PACKAGE = 'RMarkov', A, value, ptr, ind))
}

#' @export
C_sparse_to_dense_csc <- function(A, B) {
    invisible(.Call('_RMarkov_C_sparse_to_dense_csc', PACKAGE = 'RMarkov', A, B))
}

#' @export
C_create_coo <- function(A, value, row, col) {
    invisible(.Call('_RMarkov_C_create_coo', PACKAGE = 'RMarkov', A, value, row, col))
}

#' @export
C_sparse_to_dense_coo <- function(A, B) {
    invisible(.Call('_RMarkov_C_sparse_to_dense_coo', PACKAGE = 'RMarkov', A, B))
}

#' @export
C_diag_dense <- function(A) {
    .Call('_RMarkov_C_diag_dense', PACKAGE = 'RMarkov', A)
}

#' @export
C_diag_csr <- function(A) {
    .Call('_RMarkov_C_diag_csr', PACKAGE = 'RMarkov', A)
}

#' @export
C_diag_csc <- function(A) {
    .Call('_RMarkov_C_diag_csc', PACKAGE = 'RMarkov', A)
}

#' @export
C_diag_coo <- function(A) {
    .Call('_RMarkov_C_diag_coo', PACKAGE = 'RMarkov', A)
}

#' @export
C_diag_set_dense <- function(A, x) {
    invisible(.Call('_RMarkov_C_diag_set_dense', PACKAGE = 'RMarkov', A, x))
}

#' @export
C_diag_set_csr <- function(A, x) {
    invisible(.Call('_RMarkov_C_diag_set_csr', PACKAGE = 'RMarkov', A, x))
}

#' @export
C_diag_set_csc <- function(A, x) {
    invisible(.Call('_RMarkov_C_diag_set_csc', PACKAGE = 'RMarkov', A, x))
}

#' @export
C_diag_set_coo <- function(A, x) {
    invisible(.Call('_RMarkov_C_diag_set_coo', PACKAGE = 'RMarkov', A, x))
}

#' @export
C_poi_rightbound <- function(lambda, eps) {
    .Call('_RMarkov_C_poi_rightbound', PACKAGE = 'RMarkov', lambda, eps)
}

#' @export
C_poi_pmf <- function(lambda, left, right) {
    .Call('_RMarkov_C_poi_pmf', PACKAGE = 'RMarkov', lambda, left, right)
}

#' @export
C_poi_cpmf <- function(lambda, left, right) {
    .Call('_RMarkov_C_poi_cpmf', PACKAGE = 'RMarkov', lambda, left, right)
}

#' @export
C_gsstep_vecN_dense <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_vecN_dense', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_vecT_dense <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_vecT_dense', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_vecN_csr <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_vecN_csr', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_vecT_csc <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_vecT_csc', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_matN_dense <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_matN_dense', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_matT_dense <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_matT_dense', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_matN_csr <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_matN_csr', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

#' @export
C_gsstep_matT_csc <- function(alpha, A, sigma, omega, b, x0) {
    .Call('_RMarkov_C_gsstep_matT_csc', PACKAGE = 'RMarkov', alpha, A, sigma, omega, b, x0)
}

