# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ddot <- function(x, y) {
    .Call('_RMarkov_C_ddot', PACKAGE = 'RMarkov', x, y)
}

C_ddot2 <- function(x, y) {
    .Call('_RMarkov_C_ddot2', PACKAGE = 'RMarkov', x, y)
}

C_dasum <- function(x) {
    .Call('_RMarkov_C_dasum', PACKAGE = 'RMarkov', x)
}

C_dasum2 <- function(x) {
    .Call('_RMarkov_C_dasum2', PACKAGE = 'RMarkov', x)
}

C_idamax <- function(x) {
    .Call('_RMarkov_C_idamax', PACKAGE = 'RMarkov', x)
}

C_idamax2 <- function(x) {
    .Call('_RMarkov_C_idamax2', PACKAGE = 'RMarkov', x)
}

C_dcopy <- function(x, y) {
    .Call('_RMarkov_C_dcopy', PACKAGE = 'RMarkov', x, y)
}

C_dcopy2 <- function(x, y) {
    .Call('_RMarkov_C_dcopy2', PACKAGE = 'RMarkov', x, y)
}

C_dscal <- function(alpha, x) {
    .Call('_RMarkov_C_dscal', PACKAGE = 'RMarkov', alpha, x)
}

C_daxpy <- function(alpha, x, y) {
    .Call('_RMarkov_C_daxpy', PACKAGE = 'RMarkov', alpha, x, y)
}

C_dfill <- function(x, v) {
    .Call('_RMarkov_C_dfill', PACKAGE = 'RMarkov', x, v)
}

C_dgemv <- function(trans, alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemv', PACKAGE = 'RMarkov', trans, alpha, A, x, beta, y)
}

C_dger <- function(trans, alpha, x, y, A) {
    .Call('_RMarkov_C_dger', PACKAGE = 'RMarkov', trans, alpha, x, y, A)
}

C_dgemm <- function(transA, trnasB, alpha, A, B, beta, C) {
    .Call('_RMarkov_C_dgemm', PACKAGE = 'RMarkov', transA, trnasB, alpha, A, B, beta, C)
}

C_create_csr <- function(A) {
    .Call('_RMarkov_C_create_csr', PACKAGE = 'RMarkov', A)
}

C_create_dense <- function(A) {
    .Call('_RMarkov_C_create_dense', PACKAGE = 'RMarkov', A)
}

C_dgemv2 <- function(trans, alpha, A, x, beta, y) {
    .Call('_RMarkov_C_dgemv2', PACKAGE = 'RMarkov', trans, alpha, A, x, beta, y)
}

